- name: Setup mongodb
  hosts: all
  tasks:
    - name: Setup Mongodb Repo
      ansible.builtin.copy:
        src: mongo.repo
        dst: /etc/yum.repos.d/mongo.repo

    - name: Install mongodb
      ansible.builtin.dnf:
        name: mongodb-org
        state: present

    - name: Update listen address
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start mongodbservice
      ansible.builtin.systemd_service:
        name: mongod
        state: restarted
        enabled: true


