- name: Setup erlang & rabbitmq repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/{{ item }} | bash
  loop:
    - erlang/script.rpm.sh
    - rabbitmq-server/script.rpm.sh

- name: Install rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Start rabbitmq service
  ansible.builtin.systemd_services:
    name: rabbitmq
    state: restarted
    enabled: true

- name: Create app user and fix permissions
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present