- name: Add the user
  ansible.builtin.user:
    name: roboshop

- name: Delete old app dir
  ansible.builtin.file:
    state: absent
    path: /app

- name: Create new app dir
  ansible.builtin.file:
    state: directory
    path: /app

- name: Download & unzip App content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes