- name: Disable Nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodejs18
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: app_setup
  ansible.builtin.include_tasks:
    file: app_setup.yml

- name: Download App Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: load_schema
  ansible.builtin.include_tasks:
    file: mongo_schema.yml
  when: load_schema

- name: systemd_setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml

