- name: Install python
  ansible.builtin.dnf:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: App setup
  ansible.builtin.include_tasks:
    file: app_setup.yml

- name: Download Dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: systemd setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml

